version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

build:
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs
